//  fetchBalances
export const MINING_FETCH_BALANCES_BEGIN = 'MINING_FETCH_BALANCES_BEGIN';
export const MINING_FETCH_BALANCES_SUCCESS = 'MINING_FETCH_BALANCES_SUCCESS';
export const MINING_FETCH_BALANCES_FAILURE = 'MINING_FETCH_BALANCES_FAILURE';
//  fetchPoolBalances
export const MINING_FETCH_POOL_BALANCES_BEGIN = 'MINING_FETCH_POOL_BALANCES_BEGIN';
export const MINING_FETCH_POOL_BALANCES_SUCCESS = 'MINING_FETCH_POOL_BALANCES_SUCCESS';
export const MINING_FETCH_POOL_BALANCES_FAILURE = 'MINING_FETCH_POOL_BALANCES_FAILURE';
//  fetchApproval
export const MINING_FETCH_APPROVAL_BEGIN = 'MINING_FETCH_APPROVAL_BEGIN';
export const MINING_FETCH_APPROVAL_SUCCESS = 'MINING_FETCH_APPROVAL_SUCCESS';
export const MINING_FETCH_APPROVAL_FAILURE = 'MINING_FETCH_APPROVAL_FAILURE';
//  fetchFarmApporval
export const MINING_FETCH_FARM_APPROVAL_BEGIN = 'MINING_FETCH_FARM_APPROVAL_BEGIN';
export const MINING_FETCH_FARM_APPROVAL_SUCCESS = 'MINING_FETCH_FARM_APPROVAL_SUCCESS';
export const MINING_FETCH_FARM_APPROVAL_FAILURE = 'MINING_FETCH_FARM_APPROVAL_FAILURE';
//  fetchFarmAllowance
export const MINING_FETCH_FARM_ALLOWANCE_BEGIN = 'MINING_FETCH_FARM_ALLOWANCE_BEGIN';
export const MINING_FETCH_FARM_ALLOWANCE_SUCCESS = 'MINING_FETCH_FARM_ALLOWANCE_SUCCESS';
export const MINING_FETCH_FARM_ALLOWANCE_FAILURE = 'MINING_FETCH_FARM_ALLOWANCE_FAILURE';
//  fetchFarmAllowance
export const MINING_FETCH_FARM_CLAIM_BEGIN = 'MINING_FETCH_FARM_CLAIM_BEGIN';
export const MINING_FETCH_FARM_CLAIM_SUCCESS = 'MINING_FETCH_FARM_CLAIM_SUCCESS';
export const MINING_FETCH_FARM_CLAIM_FAILURE = 'MINING_FETCH_FARM_CLAIM_FAILURE';
//  fetchFarmsStaked
export const MINING_FETCH_FARMS_STAKED_BEGIN = 'MINING_FETCH_FARMS_STAKED_BEGIN';
export const MINING_FETCH_FARMS_STAKED_SUCCESS = 'MINING_FETCH_FARMS_STAKED_SUCCESS';
export const MINING_FETCH_FARMS_STAKED_FAILURE = 'MINING_FETCH_FARMS_STAKED_FAILURE';
//  fetchFarmStake
export const MINING_FETCH_FARM_STAKE_BEGIN = 'MINING_FETCH_FARM_STAKE_BEGIN';
export const MINING_FETCH_FARM_STAKE_SUCCESS = 'MINING_FETCH_FARMS_STAKE_SUCCESS';
export const MINING_FETCH_FARM_STAKE_FAILURE = 'MINING_FETCH_FARMS_STAKE_FAILURE';
//  fetchFarmUnstake
export const MINING_FETCH_FARM_UNSTAKE_BEGIN = 'MINING_FETCH_FARM_UNSTAKE_BEGIN';
export const MINING_FETCH_FARM_UNSTAKE_SUCCESS = 'MINING_FETCH_FARMS_UNSTAKE_SUCCESS';
export const MINING_FETCH_FARM_UNSTAKE_FAILURE = 'MINING_FETCH_FARMS_UNSTAKE_FAILURE';
//  fetchDeposit
export const MINING_FETCH_DEPOSIT_BEGIN = 'MINING_FETCH_DEPOSIT_BEGIN';
export const MINING_FETCH_DEPOSIT_SUCCESS = 'MINING_FETCH_DEPOSIT_SUCCESS';
export const MINING_FETCH_DEPOSIT_FAILURE = 'MINING_FETCH_DEPOSIT_FAILURE';
//  fetchWithdraw
export const MINING_FETCH_WITHDRAW_BEGIN = 'MINING_FETCH_WITHDRAW_BEGIN';
export const MINING_FETCH_WITHDRAW_SUCCESS = 'MINING_FETCH_WITHDRAW_SUCCESS';
export const MINING_FETCH_WITHDRAW_FAILURE = 'MINING_FETCH_WITHDRAW_FAILURE';
//  fetchPancakeswapPrices
export const MINING_FETCH_CONTRACT_APY_BEGIN = 'MINING_FETCH_CONTRACT_APY_BEGIN';
export const MINING_FETCH_CONTRACT_APY_SUCCESS = 'MINING_FETCH_CONTRACT_APY_SUCCESS';
export const MINING_FETCH_CONTRACT_APY_FAILURE = 'MINING_FETCH_CONTRACT_APY_FAILURE';
// fetchClaim
export const MINING_FETCH_CLAIM_BEGIN = 'MINING_FETCH_CLAIM_BEGIN';
export const MINING_FETCH_CLAIM_SUCCESS = 'MINING_FETCH_CLAIM_SUCCESS';
export const MINING_FETCH_CLAIM_FAILURE = 'MINING_FETCH_CLAIM_FAILURE';
// fetchPendingRewards
export const MINING_FETCH_PENDING_REWARDS_BEGIN = 'MINING_FETCH_PENDING_REWARDS_BEGIN';
export const MINING_FETCH_PENDING_REWARDS_SUCCESS = 'MINING_FETCH_PENDING_REWARDS_SUCCESS';
export const MINING_FETCH_PENDING_REWARDS_FAILURE = 'MINING_FETCH_PENDING_REWARDS_FAILURE';
// fetchPoolRewards
export const MINING_FETCH_POOL_REWARDS_BEGIN = 'MINING_FETCH_POOL_REWARDS_BEGIN';
export const MINING_FETCH_POOL_REWARDS_SUCCESS = 'MINING_FETCH_POOL_REWARDS_SUCCESS';
export const MINING_FETCH_POOL_REWARDS_FAILURE = 'MINING_FETCH_POOL_REWARDS_FAILURE';
// fetchFilters
export const MINING_FILTERS_SET_NETWORKS = 'MINING_FILTERS_SET_NETWORKS';
export const MINING_FILTERS_SET_CATEGORIES = 'MINING_FILTERS_SET_CATEGORIES';
export const MINING_FILTERS_SET_WITH_BALANCE = 'MINING_FILTERS_SET_WITH_BALANCE';
export const MINING_FILTERS_SET_DEPOSITED = 'MINING_FILTERS_SET_DEPOSITED';
export const MINING_FILTERS_SET_SEARCH_PHRASE = 'MINING_FILTERS_SET_SEARCH_PHRASE';
export const MINING_FILTERS_SET_SORT = 'MINING_FILTERS_SET_SORT';
export const MINING_FILTERS_RESET = 'MINING_FILTERS_RESET';